"""Save/load a ByteFractalGen checkpoint: trainable leaves + config.

Only the trainable partition (trainable_filter()) is written to disk -- frozen leaves (HiRA's
W0/A, byte_embed's table) are deterministic functions of (cfg, cfg.seed) and are regenerated by
reconstructing the skeleton model, mirroring overfitter_peft/checkpoint.py's PyTorch version
(there, W0/A are non-persistent buffers, excluded from state_dict() the same way)."""
from __future__ import annotations

import json
import os
from dataclasses import asdict

import equinox as eqx

from .model import ByteFractalGen, ModelConfig, trainable_filter


def save_model(ckpt_dir: str, model: ByteFractalGen) -> None:
    os.makedirs(ckpt_dir, exist_ok=True)
    trainable, _ = eqx.partition(model, trainable_filter(model))
    eqx.tree_serialise_leaves(os.path.join(ckpt_dir, "model.eqx"), trainable)
    with open(os.path.join(ckpt_dir, "config.json"), "w") as f:
        json.dump(asdict(model.cfg), f, indent=2)


_TUPLE_FIELDS = ("patch_len_list", "d_model_list", "n_layers_list", "n_heads_list", "mlp_mult_list")


def load_model(ckpt_dir: str) -> ByteFractalGen:
    with open(os.path.join(ckpt_dir, "config.json")) as f:
        raw = json.load(f)
    for k in _TUPLE_FIELDS:
        raw[k] = tuple(raw[k])
    cfg = ModelConfig(**raw)
    skeleton = ByteFractalGen(cfg)
    trainable_skeleton, static = eqx.partition(skeleton, trainable_filter(skeleton))
    trainable = eqx.tree_deserialise_leaves(os.path.join(ckpt_dir, "model.eqx"), trainable_skeleton)
    return eqx.combine(trainable, static)
